# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dn5RCjbFPxV2Blppp_hMADOobpBcMZ4r
"""


"""Open File"""
f = open("/content/drive/MyDrive/Colab Notebooks/access_log", "r")
Lines = f.readlines()


"""Read Status of each Log"""
status = []
for x in Lines:
  w= x.split('"')
  flag = True
  while flag == True:
    temp = w[2]
    status.append(temp[1:4])
    flag = False


"""See Unique Status"""
uniqSet= set(status)
uniqList = list(uniqSet)

"""Count status of each LOG"""
count304 = 0
count400 = 0
count200 = 0
count403 = 0
count302 = 0
count301 = 0
count404 = 0
for x in status:
  if x == uniqList[0]:
    count304 +=1   
  if x == uniqList[1]:
    count400 +=1
  if x == uniqList[2]:
    count200 +=1
  if x == uniqList[3]:
    count403 +=1
  if x == uniqList[4]:
    count302 +=1
  if x == uniqList[5]:
    count301 +=1
  if x == uniqList[6]:
    count404 +=1
print("status code 200->count {}".format(count200))
print("status code 301->count {}".format(count301))
print("status code 302->count {}".format(count302))
print("status code 304->count {}".format(count304))
print("status code 400->count {}".format(count400))
print("status code 403->count {}".format(count403))
print("status code 404->count {}".format(count404))



"""Show Status Of Each Log"""
for x in range (len(status)):
  if int(status[x]) <= 200:
    print("{} this is Successful" .format(Lines[x]))
  if int(status[x]) >= 300 and int(status[x]) <= 399:
    print("{} this is Redirect Log" .format(Lines[x]))
  if int(status[x]) >= 400 and int(status[x]) <= 499:
    print("{} this is Client errors or Failure" .format(Lines[x]))





